### ISSUE TITLE
Is it possible to return what objects are "touched" with light?

### ISSUE THREAD

**Issue by jasonmcleod** [gre/illuminated.js#10]
This library is awesome, really easy to integrate into my existing app :]

I'm looking through the code now to see about adding this feature myself. Thought I would stir the pot and see if you had any tips or plans for this.

in a tile based map, i would like to fully draw any object that has been touched with light

**Comment by gre** [comment]
Every lights have a `.bounds()` method which returns the rectangle of light bounds.
Here is how you can check if a point is potentially visible by the light:

``` javascript
var light = ...;
var point = new Vec2(x, y);
var bounds = light.bounds();
if (point.inBound(light.topleft, light.bottomright)) {
  // ...
}
```

If it's not enough for your needs and you want to **really** know if the light is actually touching the object (and there is not a opaque object between), here is how you can do it:
- Check if the point is in the light bounds (a check with the light distance can be useful also).
- Check if there is no opaque object between the point P and the light L which means no intersection between the line [P, L] and an opaque object. For polygons, you can check intersection between the line and each vertices, for circle look for "Line Circle intersection" on google.

**Comment by jasonmcleod** [comment]
Thanks for checking it out. the inBound function seems to mainly report back if the x,y falls inside of a simple shape. I am exploring the second method you mentioned - I guess i need something like Bresenham's line algorithm to check for intersections.

In my project, I'm using illuminated to achieve a "fog of war" - blocking out areas which are not in the player's line of sight. 

I'm currently clearRect'ing the solid objects and then drawing over them again with a washed out drawRect (with an alpha value based on the distance from the light)

I want to skip drawing any item which is "behind" the first object which blocks the light.

![Screen Shot 2012-12-14 at 10 13 02 AM](https://f.cloud.github.com/assets/302848/13447/acc441ae-4601-11e2-8708-39eed0401307.png)

Thanks again for the lib, and the reply!

**Comment by JCMais** [comment]
@jasonmcleod any luck with this? I'm trying to implement something similar.

**Comment by jasonmcleod** [comment]
Havent fiddled with it in a bit, I picked it up again yesterday.  I'll report back if I make any more progress. Glad someone is with me on it :)
