### ISSUE TITLE
Composite not working in Chrome Beta 27 (Android)

### ISSUE THREAD

**Issue by marksyzm** [gre/illuminated.js#15]
The answer is probably in the title (beta) but I thought I'd post this anyway. Shapes are not being drawn in the examples given here:
http://demo.greweb.fr/illuminated.js/gettingstarted.html

and on my example I've created:
http://www.oxfordsourceltd.com

This is only on Android's Chrome Beta version 27.0.1453.60

**Comment by gre** [comment]
I am using Chrome Beta 27.0.1453.60 on my Nexus 4, 
and it seems to work:

![Screenshot_2013-04-22-14-06-35](https://f.cloud.github.com/assets/211411/409034/57d16fd8-ab45-11e2-807b-a2c113a8ec02.png)

**Comment by marksyzm** [comment]
Hmmm.... mine is a Galaxy S3 and the shapes are definitely dropping out on both examples. Very strange. I'll do some testing and see if I can work it out.

**Comment by marksyzm** [comment]
Here's what I get. Glad it's slightly isolated though.
![Screenshot_2013-04-22-13-44-33](https://f.cloud.github.com/assets/420864/409162/d2a21b86-ab4a-11e2-9eb2-ec0d973f74d9.png)

**Comment by gre** [comment]
sounds a bug in Canvas impl, not handling some composite operation

2013/4/22 marksyzm notifications@github.com

> [image: Screenshot_2013-04-22-13-44-33]https://f.cloud.github.com/assets/420864/409162/d2a21b86-ab4a-11e2-9eb2-ec0d973f74d9.png
> Here's what I get
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gre/illuminated.js/issues/15#issuecomment-16783613
> .

## 

Gaëtan Renaudeau, greweb.fr

**Comment by marksyzm** [comment]
Yeah I wonder if it is, I mean it could well be... I need to hook my phone up and see what the polygon renderer is doing but don't have the time right now but I'll let you know if I do

**Comment by gre** [comment]
Ok thanks

2013/4/22 marksyzm notifications@github.com

> Yeah I wonder if it is, I mean it could well be... I need to hook my phone
> up and see what the polygon renderer is doing but don't have the time right
> now but I'll let you know if I do
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gre/illuminated.js/issues/15#issuecomment-16786312
> .

## 

Gaëtan Renaudeau, greweb.fr

**Comment by marksyzm** [comment]
Oh forgot to mention that that's all fine now! It was just a bug in chrome beta (of course) although it did find it's way, temporarily, to the release for a version or 2 also
