### ISSUE TITLE
Fix the Circle objects shadow casting

### ISSUE THREAD

**Issue by gre** [gre/illuminated.js#3]
Today we use a wrong method of casting shadows: if the light is close to a big circle, you will see the shadow projection is totally wrong:

![](http://img190.imageshack.us/img190/4230/capturedcran20120514194.png)

we need to implement this: http://en.wikipedia.org/wiki/Tangent_lines_to_circles

**Comment by josher19** [comment]
Here's one way to get the Tangents (non-optimized).

``` javascript
/** tangents from (0,0) to circle of radius a centered at (x0,y0) */
function getTangents(a,x0,y0) { 
  var t = 1/Math.cos( (-a*x0 +  y0 * Math.sqrt(x0*x0 + y0*y0 - a*a) / (x0*x0 + y0*y0) )); 
  var nt = 1/Math.cos( (-a*x0 - y0 * Math.sqrt(x0*x0 + y0*y0 - a*a) / (x0*x0 + y0*y0) ));
  var x = x0 + a*Math.cos(t);
  var y = y0 + a*Math.sin(t);
  var res = [];
  res.push(new Vec2(x,y));
  res.push(new Vec2(x0 + a*Math.cos(-t), y0 + a*Math.sin(-t)));
  if (t != nt) { 
      res.push(new Vec2(x0 + a*Math.cos(nt), y0 + a*Math.sin(nt))); 
      res.push(new Vec2(x0 + a*Math.cos(-nt), y0 + a*Math.sin(-nt))); 
  }
  return res;
}
```

Example usage for DiscObject called `that` and light source at `origin`:

``` javascript
var tangents = getTangents(that.radius, that.center.x - origin.x, that.center.y - origin.y);
```

See also: http://mathworld.wolfram.com/CircleTangentLine.html

**Comment by JCMais** [comment]
That code could be improved removing some calls to Math.sin and Math.cos, because of that:

```
 cos(-x) = cos(x)
 sin(-x) = -sin(x)
```

**Comment by gre** [comment]
Thanks for that, math is cool.

If someone would try to integrate this in the library and provide a pull request it would be perfect!

Thanks!

**Comment by josher19** [comment]
@JCMais - Okay, will optimize code in next pull request, but I think canvas rendering is the major bottleneck.

@gre - Replacing a & b in DiscObject.prototype.cast for src/illuminate.js

Let me know if you find any bugs. It had an "X" of light inside the circle in some locations, but now fixed.
![snapshot_tangent_bug_sm](https://f.cloud.github.com/assets/175075/7545/cc671bea-441b-11e2-8ca5-5d7fead9f470.png)

**Comment by josher19** [comment]
Slightly different when Light Distance/Intensity is put to max (500) and directly below the Circle.
Not noticeable at lower illumination. Might have to do with Number of Samples.
Disappears when Circle or Light are moved.

http://josher19.github.com/illuminated.js/compare.html

**Comment by gre** [comment]
Well done!
